package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JailerGraphId generated by hbm2java
 */
@Embeddable
public class JailerGraphId implements java.io.Serializable {

	private int id;
	private int age;

	public JailerGraphId() {
	}

	public JailerGraphId(int id, int age) {
		this.id = id;
		this.age = age;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JailerGraphId))
			return false;
		JailerGraphId castOther = (JailerGraphId) other;

		return (this.getId() == castOther.getId()) && (this.getAge() == castOther.getAge());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getAge();
		return result;
	}

}
