package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JailerSet generated by hbm2java
 */
@Entity
@Table(name = "jailer_set", catalog = "sakila")
public class JailerSet implements java.io.Serializable {

	private JailerSetId id;

	public JailerSet() {
	}

	public JailerSet(JailerSetId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "setId", column = @Column(name = "set_id", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 120)),
			@AttributeOverride(name = "pk0", column = @Column(name = "PK0")),
			@AttributeOverride(name = "pk1", column = @Column(name = "PK1")),
			@AttributeOverride(name = "pk2", column = @Column(name = "PK2")),
			@AttributeOverride(name = "pk3", column = @Column(name = "PK3")),
			@AttributeOverride(name = "pk4", column = @Column(name = "PK4")),
			@AttributeOverride(name = "pk5", column = @Column(name = "PK5")) })
	public JailerSetId getId() {
		return this.id;
	}

	public void setId(JailerSetId id) {
		this.id = id;
	}

}
