package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JailerEntity generated by hbm2java
 */
@Entity
@Table(name = "jailer_entity", catalog = "sakila")
public class JailerEntity implements java.io.Serializable {

	private JailerEntityId id;

	public JailerEntity() {
	}

	public JailerEntity(JailerEntityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "REntitygraph", column = @Column(name = "r_entitygraph", nullable = false)),
			@AttributeOverride(name = "pk0", column = @Column(name = "PK0")),
			@AttributeOverride(name = "pk1", column = @Column(name = "PK1")),
			@AttributeOverride(name = "pk2", column = @Column(name = "PK2")),
			@AttributeOverride(name = "pk3", column = @Column(name = "PK3")),
			@AttributeOverride(name = "pk4", column = @Column(name = "PK4")),
			@AttributeOverride(name = "pk5", column = @Column(name = "PK5")),
			@AttributeOverride(name = "birthday", column = @Column(name = "birthday", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 120)),
			@AttributeOverride(name = "prePk0", column = @Column(name = "PRE_PK0")),
			@AttributeOverride(name = "prePk1", column = @Column(name = "PRE_PK1")),
			@AttributeOverride(name = "prePk2", column = @Column(name = "PRE_PK2")),
			@AttributeOverride(name = "prePk3", column = @Column(name = "PRE_PK3")),
			@AttributeOverride(name = "prePk4", column = @Column(name = "PRE_PK4")),
			@AttributeOverride(name = "prePk5", column = @Column(name = "PRE_PK5")),
			@AttributeOverride(name = "preType", column = @Column(name = "PRE_TYPE", length = 120)),
			@AttributeOverride(name = "origBirthday", column = @Column(name = "orig_birthday")),
			@AttributeOverride(name = "association", column = @Column(name = "association")) })
	public JailerEntityId getId() {
		return this.id;
	}

	public void setId(JailerEntityId id) {
		this.id = id;
	}

}
