package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JailerGraph generated by hbm2java
 */
@Entity
@Table(name = "jailer_graph", catalog = "sakila")
public class JailerGraph implements java.io.Serializable {

	private JailerGraphId id;

	public JailerGraph() {
	}

	public JailerGraph(JailerGraphId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "age", column = @Column(name = "age", nullable = false)) })
	public JailerGraphId getId() {
		return this.id;
	}

	public void setId(JailerGraphId id) {
		this.id = id;
	}

}
