package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JailerDependencyId generated by hbm2java
 */
@Embeddable
public class JailerDependencyId implements java.io.Serializable {

	private int REntitygraph;
	private int assoc;
	private int dependId;
	private Integer traversed;
	private String fromType;
	private String toType;
	private Integer fromPk0;
	private Integer fromPk1;
	private Integer fromPk2;
	private Integer fromPk3;
	private Integer fromPk4;
	private Long fromPk5;
	private Integer toPk0;
	private Integer toPk1;
	private Integer toPk2;
	private Integer toPk3;
	private Integer toPk4;
	private Long toPk5;

	public JailerDependencyId() {
	}

	public JailerDependencyId(int REntitygraph, int assoc, int dependId, String fromType, String toType) {
		this.REntitygraph = REntitygraph;
		this.assoc = assoc;
		this.dependId = dependId;
		this.fromType = fromType;
		this.toType = toType;
	}

	public JailerDependencyId(int REntitygraph, int assoc, int dependId, Integer traversed, String fromType,
			String toType, Integer fromPk0, Integer fromPk1, Integer fromPk2, Integer fromPk3, Integer fromPk4,
			Long fromPk5, Integer toPk0, Integer toPk1, Integer toPk2, Integer toPk3, Integer toPk4, Long toPk5) {
		this.REntitygraph = REntitygraph;
		this.assoc = assoc;
		this.dependId = dependId;
		this.traversed = traversed;
		this.fromType = fromType;
		this.toType = toType;
		this.fromPk0 = fromPk0;
		this.fromPk1 = fromPk1;
		this.fromPk2 = fromPk2;
		this.fromPk3 = fromPk3;
		this.fromPk4 = fromPk4;
		this.fromPk5 = fromPk5;
		this.toPk0 = toPk0;
		this.toPk1 = toPk1;
		this.toPk2 = toPk2;
		this.toPk3 = toPk3;
		this.toPk4 = toPk4;
		this.toPk5 = toPk5;
	}

	@Column(name = "r_entitygraph", nullable = false)
	public int getREntitygraph() {
		return this.REntitygraph;
	}

	public void setREntitygraph(int REntitygraph) {
		this.REntitygraph = REntitygraph;
	}

	@Column(name = "assoc", nullable = false)
	public int getAssoc() {
		return this.assoc;
	}

	public void setAssoc(int assoc) {
		this.assoc = assoc;
	}

	@Column(name = "depend_id", nullable = false)
	public int getDependId() {
		return this.dependId;
	}

	public void setDependId(int dependId) {
		this.dependId = dependId;
	}

	@Column(name = "traversed")
	public Integer getTraversed() {
		return this.traversed;
	}

	public void setTraversed(Integer traversed) {
		this.traversed = traversed;
	}

	@Column(name = "from_type", nullable = false, length = 120)
	public String getFromType() {
		return this.fromType;
	}

	public void setFromType(String fromType) {
		this.fromType = fromType;
	}

	@Column(name = "to_type", nullable = false, length = 120)
	public String getToType() {
		return this.toType;
	}

	public void setToType(String toType) {
		this.toType = toType;
	}

	@Column(name = "FROM_PK0")
	public Integer getFromPk0() {
		return this.fromPk0;
	}

	public void setFromPk0(Integer fromPk0) {
		this.fromPk0 = fromPk0;
	}

	@Column(name = "FROM_PK1")
	public Integer getFromPk1() {
		return this.fromPk1;
	}

	public void setFromPk1(Integer fromPk1) {
		this.fromPk1 = fromPk1;
	}

	@Column(name = "FROM_PK2")
	public Integer getFromPk2() {
		return this.fromPk2;
	}

	public void setFromPk2(Integer fromPk2) {
		this.fromPk2 = fromPk2;
	}

	@Column(name = "FROM_PK3")
	public Integer getFromPk3() {
		return this.fromPk3;
	}

	public void setFromPk3(Integer fromPk3) {
		this.fromPk3 = fromPk3;
	}

	@Column(name = "FROM_PK4")
	public Integer getFromPk4() {
		return this.fromPk4;
	}

	public void setFromPk4(Integer fromPk4) {
		this.fromPk4 = fromPk4;
	}

	@Column(name = "FROM_PK5")
	public Long getFromPk5() {
		return this.fromPk5;
	}

	public void setFromPk5(Long fromPk5) {
		this.fromPk5 = fromPk5;
	}

	@Column(name = "TO_PK0")
	public Integer getToPk0() {
		return this.toPk0;
	}

	public void setToPk0(Integer toPk0) {
		this.toPk0 = toPk0;
	}

	@Column(name = "TO_PK1")
	public Integer getToPk1() {
		return this.toPk1;
	}

	public void setToPk1(Integer toPk1) {
		this.toPk1 = toPk1;
	}

	@Column(name = "TO_PK2")
	public Integer getToPk2() {
		return this.toPk2;
	}

	public void setToPk2(Integer toPk2) {
		this.toPk2 = toPk2;
	}

	@Column(name = "TO_PK3")
	public Integer getToPk3() {
		return this.toPk3;
	}

	public void setToPk3(Integer toPk3) {
		this.toPk3 = toPk3;
	}

	@Column(name = "TO_PK4")
	public Integer getToPk4() {
		return this.toPk4;
	}

	public void setToPk4(Integer toPk4) {
		this.toPk4 = toPk4;
	}

	@Column(name = "TO_PK5")
	public Long getToPk5() {
		return this.toPk5;
	}

	public void setToPk5(Long toPk5) {
		this.toPk5 = toPk5;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JailerDependencyId))
			return false;
		JailerDependencyId castOther = (JailerDependencyId) other;

		return (this.getREntitygraph() == castOther.getREntitygraph()) && (this.getAssoc() == castOther.getAssoc())
				&& (this.getDependId() == castOther.getDependId())
				&& ((this.getTraversed() == castOther.getTraversed()) || (this.getTraversed() != null
						&& castOther.getTraversed() != null && this.getTraversed().equals(castOther.getTraversed())))
				&& ((this.getFromType() == castOther.getFromType()) || (this.getFromType() != null
						&& castOther.getFromType() != null && this.getFromType().equals(castOther.getFromType())))
				&& ((this.getToType() == castOther.getToType()) || (this.getToType() != null
						&& castOther.getToType() != null && this.getToType().equals(castOther.getToType())))
				&& ((this.getFromPk0() == castOther.getFromPk0()) || (this.getFromPk0() != null
						&& castOther.getFromPk0() != null && this.getFromPk0().equals(castOther.getFromPk0())))
				&& ((this.getFromPk1() == castOther.getFromPk1()) || (this.getFromPk1() != null
						&& castOther.getFromPk1() != null && this.getFromPk1().equals(castOther.getFromPk1())))
				&& ((this.getFromPk2() == castOther.getFromPk2()) || (this.getFromPk2() != null
						&& castOther.getFromPk2() != null && this.getFromPk2().equals(castOther.getFromPk2())))
				&& ((this.getFromPk3() == castOther.getFromPk3()) || (this.getFromPk3() != null
						&& castOther.getFromPk3() != null && this.getFromPk3().equals(castOther.getFromPk3())))
				&& ((this.getFromPk4() == castOther.getFromPk4()) || (this.getFromPk4() != null
						&& castOther.getFromPk4() != null && this.getFromPk4().equals(castOther.getFromPk4())))
				&& ((this.getFromPk5() == castOther.getFromPk5()) || (this.getFromPk5() != null
						&& castOther.getFromPk5() != null && this.getFromPk5().equals(castOther.getFromPk5())))
				&& ((this.getToPk0() == castOther.getToPk0()) || (this.getToPk0() != null
						&& castOther.getToPk0() != null && this.getToPk0().equals(castOther.getToPk0())))
				&& ((this.getToPk1() == castOther.getToPk1()) || (this.getToPk1() != null
						&& castOther.getToPk1() != null && this.getToPk1().equals(castOther.getToPk1())))
				&& ((this.getToPk2() == castOther.getToPk2()) || (this.getToPk2() != null
						&& castOther.getToPk2() != null && this.getToPk2().equals(castOther.getToPk2())))
				&& ((this.getToPk3() == castOther.getToPk3()) || (this.getToPk3() != null
						&& castOther.getToPk3() != null && this.getToPk3().equals(castOther.getToPk3())))
				&& ((this.getToPk4() == castOther.getToPk4()) || (this.getToPk4() != null
						&& castOther.getToPk4() != null && this.getToPk4().equals(castOther.getToPk4())))
				&& ((this.getToPk5() == castOther.getToPk5()) || (this.getToPk5() != null
						&& castOther.getToPk5() != null && this.getToPk5().equals(castOther.getToPk5())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getREntitygraph();
		result = 37 * result + this.getAssoc();
		result = 37 * result + this.getDependId();
		result = 37 * result + (getTraversed() == null ? 0 : this.getTraversed().hashCode());
		result = 37 * result + (getFromType() == null ? 0 : this.getFromType().hashCode());
		result = 37 * result + (getToType() == null ? 0 : this.getToType().hashCode());
		result = 37 * result + (getFromPk0() == null ? 0 : this.getFromPk0().hashCode());
		result = 37 * result + (getFromPk1() == null ? 0 : this.getFromPk1().hashCode());
		result = 37 * result + (getFromPk2() == null ? 0 : this.getFromPk2().hashCode());
		result = 37 * result + (getFromPk3() == null ? 0 : this.getFromPk3().hashCode());
		result = 37 * result + (getFromPk4() == null ? 0 : this.getFromPk4().hashCode());
		result = 37 * result + (getFromPk5() == null ? 0 : this.getFromPk5().hashCode());
		result = 37 * result + (getToPk0() == null ? 0 : this.getToPk0().hashCode());
		result = 37 * result + (getToPk1() == null ? 0 : this.getToPk1().hashCode());
		result = 37 * result + (getToPk2() == null ? 0 : this.getToPk2().hashCode());
		result = 37 * result + (getToPk3() == null ? 0 : this.getToPk3().hashCode());
		result = 37 * result + (getToPk4() == null ? 0 : this.getToPk4().hashCode());
		result = 37 * result + (getToPk5() == null ? 0 : this.getToPk5().hashCode());
		return result;
	}

}
