package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JailerSetId generated by hbm2java
 */
@Embeddable
public class JailerSetId implements java.io.Serializable {

	private int setId;
	private String type;
	private Integer pk0;
	private Integer pk1;
	private Integer pk2;
	private Integer pk3;
	private Integer pk4;
	private Long pk5;

	public JailerSetId() {
	}

	public JailerSetId(int setId, String type) {
		this.setId = setId;
		this.type = type;
	}

	public JailerSetId(int setId, String type, Integer pk0, Integer pk1, Integer pk2, Integer pk3, Integer pk4,
			Long pk5) {
		this.setId = setId;
		this.type = type;
		this.pk0 = pk0;
		this.pk1 = pk1;
		this.pk2 = pk2;
		this.pk3 = pk3;
		this.pk4 = pk4;
		this.pk5 = pk5;
	}

	@Column(name = "set_id", nullable = false)
	public int getSetId() {
		return this.setId;
	}

	public void setSetId(int setId) {
		this.setId = setId;
	}

	@Column(name = "type", nullable = false, length = 120)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "PK0")
	public Integer getPk0() {
		return this.pk0;
	}

	public void setPk0(Integer pk0) {
		this.pk0 = pk0;
	}

	@Column(name = "PK1")
	public Integer getPk1() {
		return this.pk1;
	}

	public void setPk1(Integer pk1) {
		this.pk1 = pk1;
	}

	@Column(name = "PK2")
	public Integer getPk2() {
		return this.pk2;
	}

	public void setPk2(Integer pk2) {
		this.pk2 = pk2;
	}

	@Column(name = "PK3")
	public Integer getPk3() {
		return this.pk3;
	}

	public void setPk3(Integer pk3) {
		this.pk3 = pk3;
	}

	@Column(name = "PK4")
	public Integer getPk4() {
		return this.pk4;
	}

	public void setPk4(Integer pk4) {
		this.pk4 = pk4;
	}

	@Column(name = "PK5")
	public Long getPk5() {
		return this.pk5;
	}

	public void setPk5(Long pk5) {
		this.pk5 = pk5;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JailerSetId))
			return false;
		JailerSetId castOther = (JailerSetId) other;

		return (this.getSetId() == castOther.getSetId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getPk0() == castOther.getPk0()) || (this.getPk0() != null && castOther.getPk0() != null
						&& this.getPk0().equals(castOther.getPk0())))
				&& ((this.getPk1() == castOther.getPk1()) || (this.getPk1() != null && castOther.getPk1() != null
						&& this.getPk1().equals(castOther.getPk1())))
				&& ((this.getPk2() == castOther.getPk2()) || (this.getPk2() != null && castOther.getPk2() != null
						&& this.getPk2().equals(castOther.getPk2())))
				&& ((this.getPk3() == castOther.getPk3()) || (this.getPk3() != null && castOther.getPk3() != null
						&& this.getPk3().equals(castOther.getPk3())))
				&& ((this.getPk4() == castOther.getPk4()) || (this.getPk4() != null && castOther.getPk4() != null
						&& this.getPk4().equals(castOther.getPk4())))
				&& ((this.getPk5() == castOther.getPk5()) || (this.getPk5() != null && castOther.getPk5() != null
						&& this.getPk5().equals(castOther.getPk5())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSetId();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getPk0() == null ? 0 : this.getPk0().hashCode());
		result = 37 * result + (getPk1() == null ? 0 : this.getPk1().hashCode());
		result = 37 * result + (getPk2() == null ? 0 : this.getPk2().hashCode());
		result = 37 * result + (getPk3() == null ? 0 : this.getPk3().hashCode());
		result = 37 * result + (getPk4() == null ? 0 : this.getPk4().hashCode());
		result = 37 * result + (getPk5() == null ? 0 : this.getPk5().hashCode());
		return result;
	}

}
