package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JailerTmpId generated by hbm2java
 */
@Embeddable
public class JailerTmpId implements java.io.Serializable {

	private Integer c1;
	private Integer c2;

	public JailerTmpId() {
	}

	public JailerTmpId(Integer c1, Integer c2) {
		this.c1 = c1;
		this.c2 = c2;
	}

	@Column(name = "c1")
	public Integer getC1() {
		return this.c1;
	}

	public void setC1(Integer c1) {
		this.c1 = c1;
	}

	@Column(name = "c2")
	public Integer getC2() {
		return this.c2;
	}

	public void setC2(Integer c2) {
		this.c2 = c2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JailerTmpId))
			return false;
		JailerTmpId castOther = (JailerTmpId) other;

		return ((this.getC1() == castOther.getC1())
				|| (this.getC1() != null && castOther.getC1() != null && this.getC1().equals(castOther.getC1())))
				&& ((this.getC2() == castOther.getC2()) || (this.getC2() != null && castOther.getC2() != null
						&& this.getC2().equals(castOther.getC2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getC1() == null ? 0 : this.getC1().hashCode());
		result = 37 * result + (getC2() == null ? 0 : this.getC2().hashCode());
		return result;
	}

}
