package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JailerEntityId generated by hbm2java
 */
@Embeddable
public class JailerEntityId implements java.io.Serializable {

	private int REntitygraph;
	private Integer pk0;
	private Integer pk1;
	private Integer pk2;
	private Integer pk3;
	private Integer pk4;
	private Long pk5;
	private int birthday;
	private String type;
	private Integer prePk0;
	private Integer prePk1;
	private Integer prePk2;
	private Integer prePk3;
	private Integer prePk4;
	private Long prePk5;
	private String preType;
	private Integer origBirthday;
	private Integer association;

	public JailerEntityId() {
	}

	public JailerEntityId(int REntitygraph, int birthday, String type) {
		this.REntitygraph = REntitygraph;
		this.birthday = birthday;
		this.type = type;
	}

	public JailerEntityId(int REntitygraph, Integer pk0, Integer pk1, Integer pk2, Integer pk3, Integer pk4, Long pk5,
			int birthday, String type, Integer prePk0, Integer prePk1, Integer prePk2, Integer prePk3, Integer prePk4,
			Long prePk5, String preType, Integer origBirthday, Integer association) {
		this.REntitygraph = REntitygraph;
		this.pk0 = pk0;
		this.pk1 = pk1;
		this.pk2 = pk2;
		this.pk3 = pk3;
		this.pk4 = pk4;
		this.pk5 = pk5;
		this.birthday = birthday;
		this.type = type;
		this.prePk0 = prePk0;
		this.prePk1 = prePk1;
		this.prePk2 = prePk2;
		this.prePk3 = prePk3;
		this.prePk4 = prePk4;
		this.prePk5 = prePk5;
		this.preType = preType;
		this.origBirthday = origBirthday;
		this.association = association;
	}

	@Column(name = "r_entitygraph", nullable = false)
	public int getREntitygraph() {
		return this.REntitygraph;
	}

	public void setREntitygraph(int REntitygraph) {
		this.REntitygraph = REntitygraph;
	}

	@Column(name = "PK0")
	public Integer getPk0() {
		return this.pk0;
	}

	public void setPk0(Integer pk0) {
		this.pk0 = pk0;
	}

	@Column(name = "PK1")
	public Integer getPk1() {
		return this.pk1;
	}

	public void setPk1(Integer pk1) {
		this.pk1 = pk1;
	}

	@Column(name = "PK2")
	public Integer getPk2() {
		return this.pk2;
	}

	public void setPk2(Integer pk2) {
		this.pk2 = pk2;
	}

	@Column(name = "PK3")
	public Integer getPk3() {
		return this.pk3;
	}

	public void setPk3(Integer pk3) {
		this.pk3 = pk3;
	}

	@Column(name = "PK4")
	public Integer getPk4() {
		return this.pk4;
	}

	public void setPk4(Integer pk4) {
		this.pk4 = pk4;
	}

	@Column(name = "PK5")
	public Long getPk5() {
		return this.pk5;
	}

	public void setPk5(Long pk5) {
		this.pk5 = pk5;
	}

	@Column(name = "birthday", nullable = false)
	public int getBirthday() {
		return this.birthday;
	}

	public void setBirthday(int birthday) {
		this.birthday = birthday;
	}

	@Column(name = "type", nullable = false, length = 120)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "PRE_PK0")
	public Integer getPrePk0() {
		return this.prePk0;
	}

	public void setPrePk0(Integer prePk0) {
		this.prePk0 = prePk0;
	}

	@Column(name = "PRE_PK1")
	public Integer getPrePk1() {
		return this.prePk1;
	}

	public void setPrePk1(Integer prePk1) {
		this.prePk1 = prePk1;
	}

	@Column(name = "PRE_PK2")
	public Integer getPrePk2() {
		return this.prePk2;
	}

	public void setPrePk2(Integer prePk2) {
		this.prePk2 = prePk2;
	}

	@Column(name = "PRE_PK3")
	public Integer getPrePk3() {
		return this.prePk3;
	}

	public void setPrePk3(Integer prePk3) {
		this.prePk3 = prePk3;
	}

	@Column(name = "PRE_PK4")
	public Integer getPrePk4() {
		return this.prePk4;
	}

	public void setPrePk4(Integer prePk4) {
		this.prePk4 = prePk4;
	}

	@Column(name = "PRE_PK5")
	public Long getPrePk5() {
		return this.prePk5;
	}

	public void setPrePk5(Long prePk5) {
		this.prePk5 = prePk5;
	}

	@Column(name = "PRE_TYPE", length = 120)
	public String getPreType() {
		return this.preType;
	}

	public void setPreType(String preType) {
		this.preType = preType;
	}

	@Column(name = "orig_birthday")
	public Integer getOrigBirthday() {
		return this.origBirthday;
	}

	public void setOrigBirthday(Integer origBirthday) {
		this.origBirthday = origBirthday;
	}

	@Column(name = "association")
	public Integer getAssociation() {
		return this.association;
	}

	public void setAssociation(Integer association) {
		this.association = association;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JailerEntityId))
			return false;
		JailerEntityId castOther = (JailerEntityId) other;

		return (this.getREntitygraph() == castOther.getREntitygraph()) && ((this.getPk0() == castOther.getPk0())
				|| (this.getPk0() != null && castOther.getPk0() != null && this.getPk0().equals(castOther.getPk0())))
				&& ((this.getPk1() == castOther.getPk1()) || (this.getPk1() != null && castOther.getPk1() != null
						&& this.getPk1().equals(castOther.getPk1())))
				&& ((this.getPk2() == castOther.getPk2()) || (this.getPk2() != null && castOther.getPk2() != null
						&& this.getPk2().equals(castOther.getPk2())))
				&& ((this.getPk3() == castOther.getPk3()) || (this.getPk3() != null && castOther.getPk3() != null
						&& this.getPk3().equals(castOther.getPk3())))
				&& ((this.getPk4() == castOther.getPk4()) || (this.getPk4() != null && castOther.getPk4() != null
						&& this.getPk4().equals(castOther.getPk4())))
				&& ((this.getPk5() == castOther.getPk5()) || (this.getPk5() != null
						&& castOther.getPk5() != null && this.getPk5().equals(castOther.getPk5())))
				&& (this.getBirthday() == castOther.getBirthday())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getPrePk0() == castOther.getPrePk0()) || (this.getPrePk0() != null
						&& castOther.getPrePk0() != null && this.getPrePk0().equals(castOther.getPrePk0())))
				&& ((this.getPrePk1() == castOther.getPrePk1()) || (this.getPrePk1() != null
						&& castOther.getPrePk1() != null && this.getPrePk1().equals(castOther.getPrePk1())))
				&& ((this.getPrePk2() == castOther.getPrePk2()) || (this.getPrePk2() != null
						&& castOther.getPrePk2() != null && this.getPrePk2().equals(castOther.getPrePk2())))
				&& ((this.getPrePk3() == castOther.getPrePk3()) || (this.getPrePk3() != null
						&& castOther.getPrePk3() != null && this.getPrePk3().equals(castOther.getPrePk3())))
				&& ((this.getPrePk4() == castOther.getPrePk4()) || (this.getPrePk4() != null
						&& castOther.getPrePk4() != null && this.getPrePk4().equals(castOther.getPrePk4())))
				&& ((this.getPrePk5() == castOther.getPrePk5()) || (this.getPrePk5() != null
						&& castOther.getPrePk5() != null && this.getPrePk5().equals(castOther.getPrePk5())))
				&& ((this.getPreType() == castOther.getPreType()) || (this.getPreType() != null
						&& castOther.getPreType() != null && this.getPreType().equals(castOther.getPreType())))
				&& ((this.getOrigBirthday() == castOther.getOrigBirthday())
						|| (this.getOrigBirthday() != null && castOther.getOrigBirthday() != null
								&& this.getOrigBirthday().equals(castOther.getOrigBirthday())))
				&& ((this.getAssociation() == castOther.getAssociation())
						|| (this.getAssociation() != null && castOther.getAssociation() != null
								&& this.getAssociation().equals(castOther.getAssociation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getREntitygraph();
		result = 37 * result + (getPk0() == null ? 0 : this.getPk0().hashCode());
		result = 37 * result + (getPk1() == null ? 0 : this.getPk1().hashCode());
		result = 37 * result + (getPk2() == null ? 0 : this.getPk2().hashCode());
		result = 37 * result + (getPk3() == null ? 0 : this.getPk3().hashCode());
		result = 37 * result + (getPk4() == null ? 0 : this.getPk4().hashCode());
		result = 37 * result + (getPk5() == null ? 0 : this.getPk5().hashCode());
		result = 37 * result + this.getBirthday();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getPrePk0() == null ? 0 : this.getPrePk0().hashCode());
		result = 37 * result + (getPrePk1() == null ? 0 : this.getPrePk1().hashCode());
		result = 37 * result + (getPrePk2() == null ? 0 : this.getPrePk2().hashCode());
		result = 37 * result + (getPrePk3() == null ? 0 : this.getPrePk3().hashCode());
		result = 37 * result + (getPrePk4() == null ? 0 : this.getPrePk4().hashCode());
		result = 37 * result + (getPrePk5() == null ? 0 : this.getPrePk5().hashCode());
		result = 37 * result + (getPreType() == null ? 0 : this.getPreType().hashCode());
		result = 37 * result + (getOrigBirthday() == null ? 0 : this.getOrigBirthday().hashCode());
		result = 37 * result + (getAssociation() == null ? 0 : this.getAssociation().hashCode());
		return result;
	}

}
