package com.sakila.entities;
// Generated Nov 10, 2017 10:25:35 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JailerDependency generated by hbm2java
 */
@Entity
@Table(name = "jailer_dependency", catalog = "sakila")
public class JailerDependency implements java.io.Serializable {

	private JailerDependencyId id;

	public JailerDependency() {
	}

	public JailerDependency(JailerDependencyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "REntitygraph", column = @Column(name = "r_entitygraph", nullable = false)),
			@AttributeOverride(name = "assoc", column = @Column(name = "assoc", nullable = false)),
			@AttributeOverride(name = "dependId", column = @Column(name = "depend_id", nullable = false)),
			@AttributeOverride(name = "traversed", column = @Column(name = "traversed")),
			@AttributeOverride(name = "fromType", column = @Column(name = "from_type", nullable = false, length = 120)),
			@AttributeOverride(name = "toType", column = @Column(name = "to_type", nullable = false, length = 120)),
			@AttributeOverride(name = "fromPk0", column = @Column(name = "FROM_PK0")),
			@AttributeOverride(name = "fromPk1", column = @Column(name = "FROM_PK1")),
			@AttributeOverride(name = "fromPk2", column = @Column(name = "FROM_PK2")),
			@AttributeOverride(name = "fromPk3", column = @Column(name = "FROM_PK3")),
			@AttributeOverride(name = "fromPk4", column = @Column(name = "FROM_PK4")),
			@AttributeOverride(name = "fromPk5", column = @Column(name = "FROM_PK5")),
			@AttributeOverride(name = "toPk0", column = @Column(name = "TO_PK0")),
			@AttributeOverride(name = "toPk1", column = @Column(name = "TO_PK1")),
			@AttributeOverride(name = "toPk2", column = @Column(name = "TO_PK2")),
			@AttributeOverride(name = "toPk3", column = @Column(name = "TO_PK3")),
			@AttributeOverride(name = "toPk4", column = @Column(name = "TO_PK4")),
			@AttributeOverride(name = "toPk5", column = @Column(name = "TO_PK5")) })
	public JailerDependencyId getId() {
		return this.id;
	}

	public void setId(JailerDependencyId id) {
		this.id = id;
	}

}
